# common variables:
id_list = []
tweet_list = []

hello0 = '[Executed in Normal Mode]'
CK0  = 'XXXXXXXXXXXXXXXXXXXXXXXXX'        
CS0  = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
AT0  = 'XXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
AS0  = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'